// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmpsewirwzhvwmyjvcse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcHNld2lyd3podndteWp2Y3NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzU3NjgsImV4cCI6MjA2NTQxMTc2OH0._6myosK7ewwGXmP5VED2AfDdkCBjCi5QOSDCC6mnVkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);